apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # This is the 'Application' for the ingress
  name: argocd-ingress
  namespace: argocd # This manifest itself lives in the 'argocd' namespace
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/rajnish-init/k8s-yaml-manifests.git
    targetRevision: HEAD
    path: system/argocd # <-- Tells Argo to watch this new path
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd # <-- Tells Argo to deploy the ingress INTO the 'argocd' namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true