apiVersion: v1
kind: Service
metadata:
  name: my-mongo-db-0
  namespace: mongodb
spec:
  type: LoadBalancer
  selector:
    statefulset.kubernetes.io/pod-name: my-mongo-db-0
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: my-mongo-db-1
  namespace: mongodb
spec:
  type: LoadBalancer
  selector:
    statefulset.kubernetes.io/pod-name: my-mongo-db-1
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017